/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  ExampleScript1,
  ExampleScript1Interface,
} from "../ExampleScript1";

const _abi = [
  {
    inputs: [],
    name: "run",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5060b88061001f6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063c040622614602d575b600080fd5b60336047565b604051603e9190605d565b60405180910390f35b60006001905090565b6057816076565b82525050565b6000602082019050607060008301846050565b92915050565b6000811515905091905056fea264697066735822122018ad01b6862ff64d979da86b7bcfd4de1a90a6f7f259817f4bb086fbd3b8019664736f6c63430008040033";

type ExampleScript1ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ExampleScript1ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ExampleScript1__factory extends ContractFactory {
  constructor(...args: ExampleScript1ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ExampleScript1> {
    return super.deploy(overrides || {}) as Promise<ExampleScript1>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): ExampleScript1 {
    return super.attach(address) as ExampleScript1;
  }
  connect(signer: Signer): ExampleScript1__factory {
    return super.connect(signer) as ExampleScript1__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ExampleScript1Interface {
    return new utils.Interface(_abi) as ExampleScript1Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ExampleScript1 {
    return new Contract(address, _abi, signerOrProvider) as ExampleScript1;
  }
}
