/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  ExampleScript3,
  ExampleScript3Interface,
} from "../ExampleScript3";

const _abi = [
  {
    inputs: [],
    name: "run",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5060b88061001f6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063c040622614602d575b600080fd5b60336047565b604051603e9190605d565b60405180910390f35b60006001905090565b6057816076565b82525050565b6000602082019050607060008301846050565b92915050565b6000811515905091905056fea2646970667358221220febdc522c79c892d5a2ad6472d32cd6ce5a1f38fc3ca10464294df6ca408430764736f6c63430008040033";

type ExampleScript3ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ExampleScript3ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ExampleScript3__factory extends ContractFactory {
  constructor(...args: ExampleScript3ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ExampleScript3> {
    return super.deploy(overrides || {}) as Promise<ExampleScript3>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): ExampleScript3 {
    return super.attach(address) as ExampleScript3;
  }
  connect(signer: Signer): ExampleScript3__factory {
    return super.connect(signer) as ExampleScript3__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ExampleScript3Interface {
    return new utils.Interface(_abi) as ExampleScript3Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ExampleScript3 {
    return new Contract(address, _abi, signerOrProvider) as ExampleScript3;
  }
}
