/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IScript, IScriptInterface } from "../IScript";

const _abi = [
  {
    inputs: [],
    name: "run",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IScript__factory {
  static readonly abi = _abi;
  static createInterface(): IScriptInterface {
    return new utils.Interface(_abi) as IScriptInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IScript {
    return new Contract(address, _abi, signerOrProvider) as IScript;
  }
}
