/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { Signal, SignalInterface } from "../Signal";

const _abi = [
  {
    inputs: [],
    name: "yesOrNo",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class Signal__factory {
  static readonly abi = _abi;
  static createInterface(): SignalInterface {
    return new utils.Interface(_abi) as SignalInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Signal {
    return new Contract(address, _abi, signerOrProvider) as Signal;
  }
}
