/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
<<<<<<< HEAD
      name: "ActionState",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ActionState__factory>;
=======
      name: "ExampleScript1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ExampleScript1__factory>;
>>>>>>> 09bc438 (chore: Add typechain)
    getContractFactory(
      name: "IScript",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IScript__factory>;
    getContractFactory(
<<<<<<< HEAD
      name: "MerkleProofWrapper",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MerkleProofWrapper__factory>;
    getContractFactory(
      name: "ExampleScriptSpeedBump",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ExampleScriptSpeedBump__factory>;
    getContractFactory(
      name: "ExampleScript1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ExampleScript1__factory>;
    getContractFactory(
      name: "ExampleScript2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ExampleScript2__factory>;
=======
      name: "ScriptTree",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ScriptTree__factory>;
    getContractFactory(
      name: "TestScript1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TestScript1__factory>;
>>>>>>> 09bc438 (chore: Add typechain)
    getContractFactory(
      name: "Signal",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Signal__factory>;
    getContractFactory(
<<<<<<< HEAD
      name: "ExampleScript3",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ExampleScript3__factory>;
    getContractFactory(
      name: "ScriptTree",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ScriptTree__factory>;

    getContractAt(
      name: "ActionState",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ActionState>;
=======
      name: "TestScript2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TestScript2__factory>;

    getContractAt(
      name: "ExampleScript1",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ExampleScript1>;
>>>>>>> 09bc438 (chore: Add typechain)
    getContractAt(
      name: "IScript",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IScript>;
    getContractAt(
<<<<<<< HEAD
      name: "MerkleProofWrapper",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MerkleProofWrapper>;
    getContractAt(
      name: "ExampleScriptSpeedBump",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ExampleScriptSpeedBump>;
    getContractAt(
      name: "ExampleScript1",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ExampleScript1>;
    getContractAt(
      name: "ExampleScript2",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ExampleScript2>;
=======
      name: "ScriptTree",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ScriptTree>;
    getContractAt(
      name: "TestScript1",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.TestScript1>;
>>>>>>> 09bc438 (chore: Add typechain)
    getContractAt(
      name: "Signal",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Signal>;
    getContractAt(
<<<<<<< HEAD
      name: "ExampleScript3",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ExampleScript3>;
    getContractAt(
      name: "ScriptTree",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ScriptTree>;
=======
      name: "TestScript2",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.TestScript2>;
>>>>>>> 09bc438 (chore: Add typechain)

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
