/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface ScriptTreeInterface extends ethers.utils.Interface {
  functions: {
    "execute(address,uint256,bytes,bytes,bytes32[])": FunctionFragment;
    "scriptsRoot()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "execute",
    values: [string, BigNumberish, BytesLike, BytesLike, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "scriptsRoot",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "scriptsRoot",
    data: BytesLike
  ): Result;

  events: {
    "ScriptSpent(bytes32,address,uint256,bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ScriptSpent"): EventFragment;
}

export type ScriptSpentEvent = TypedEvent<
  [string, string, BigNumber, string],
  { scriptHash: string; to: string; value: BigNumber; data: string }
>;

export type ScriptSpentEventFilter = TypedEventFilter<ScriptSpentEvent>;

export interface ScriptTree extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ScriptTreeInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    execute(
      _to: string,
      _value: BigNumberish,
      _data: BytesLike,
      _script: BytesLike,
      _proof: BytesLike[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    scriptsRoot(overrides?: CallOverrides): Promise<[string]>;
  };

  execute(
    _to: string,
    _value: BigNumberish,
    _data: BytesLike,
    _script: BytesLike,
    _proof: BytesLike[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  scriptsRoot(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    execute(
      _to: string,
      _value: BigNumberish,
      _data: BytesLike,
      _script: BytesLike,
      _proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    scriptsRoot(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "ScriptSpent(bytes32,address,uint256,bytes)"(
      scriptHash?: BytesLike | null,
      to?: string | null,
      value?: null,
      data?: null
    ): ScriptSpentEventFilter;
    ScriptSpent(
      scriptHash?: BytesLike | null,
      to?: string | null,
      value?: null,
      data?: null
    ): ScriptSpentEventFilter;
  };

  estimateGas: {
    execute(
      _to: string,
      _value: BigNumberish,
      _data: BytesLike,
      _script: BytesLike,
      _proof: BytesLike[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    scriptsRoot(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    execute(
      _to: string,
      _value: BigNumberish,
      _data: BytesLike,
      _script: BytesLike,
      _proof: BytesLike[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    scriptsRoot(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
