/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface ScriptTreeInterface extends ethers.utils.Interface {
  functions: {
    "conditionsRoot()": FunctionFragment;
<<<<<<< HEAD
    "lastAction()": FunctionFragment;
    "numActions()": FunctionFragment;
    "pendingAction()": FunctionFragment;
=======
>>>>>>> 09bc438 (chore: Add typechain)
    "spend(address,uint256,bytes,bytes,bytes32[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "conditionsRoot",
    values?: undefined
  ): string;
  encodeFunctionData(
<<<<<<< HEAD
    functionFragment: "lastAction",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "numActions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingAction",
    values?: undefined
  ): string;
  encodeFunctionData(
=======
>>>>>>> 09bc438 (chore: Add typechain)
    functionFragment: "spend",
    values: [string, BigNumberish, BytesLike, BytesLike, BytesLike[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "conditionsRoot",
    data: BytesLike
  ): Result;
<<<<<<< HEAD
  decodeFunctionResult(functionFragment: "lastAction", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "numActions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "spend", data: BytesLike): Result;

  events: {
    "ScriptSpent(bytes32,address,uint256,bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ScriptSpent"): EventFragment;
}

export type ScriptSpentEvent = TypedEvent<
  [string, string, BigNumber, string],
  { scriptHash: string; to: string; value: BigNumber; data: string }
>;

export type ScriptSpentEventFilter = TypedEventFilter<ScriptSpentEvent>;

=======
  decodeFunctionResult(functionFragment: "spend", data: BytesLike): Result;

  events: {};
}

>>>>>>> 09bc438 (chore: Add typechain)
export interface ScriptTree extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ScriptTreeInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    conditionsRoot(overrides?: CallOverrides): Promise<[string]>;

<<<<<<< HEAD
    lastAction(
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, string, BigNumber] & {
        to: string;
        value: BigNumber;
        data: string;
        timestamp: BigNumber;
      }
    >;

    numActions(overrides?: CallOverrides): Promise<[BigNumber]>;

    pendingAction(
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, string, BigNumber] & {
        to: string;
        value: BigNumber;
        data: string;
        timestamp: BigNumber;
      }
    >;

=======
>>>>>>> 09bc438 (chore: Add typechain)
    spend(
      _to: string,
      _value: BigNumberish,
      _data: BytesLike,
      _script: BytesLike,
      _proof: BytesLike[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  conditionsRoot(overrides?: CallOverrides): Promise<string>;

<<<<<<< HEAD
  lastAction(
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, string, BigNumber] & {
      to: string;
      value: BigNumber;
      data: string;
      timestamp: BigNumber;
    }
  >;

  numActions(overrides?: CallOverrides): Promise<BigNumber>;

  pendingAction(
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, string, BigNumber] & {
      to: string;
      value: BigNumber;
      data: string;
      timestamp: BigNumber;
    }
  >;

=======
>>>>>>> 09bc438 (chore: Add typechain)
  spend(
    _to: string,
    _value: BigNumberish,
    _data: BytesLike,
    _script: BytesLike,
    _proof: BytesLike[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    conditionsRoot(overrides?: CallOverrides): Promise<string>;

<<<<<<< HEAD
    lastAction(
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, string, BigNumber] & {
        to: string;
        value: BigNumber;
        data: string;
        timestamp: BigNumber;
      }
    >;

    numActions(overrides?: CallOverrides): Promise<BigNumber>;

    pendingAction(
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, string, BigNumber] & {
        to: string;
        value: BigNumber;
        data: string;
        timestamp: BigNumber;
      }
    >;

=======
>>>>>>> 09bc438 (chore: Add typechain)
    spend(
      _to: string,
      _value: BigNumberish,
      _data: BytesLike,
      _script: BytesLike,
      _proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

<<<<<<< HEAD
  filters: {
    "ScriptSpent(bytes32,address,uint256,bytes)"(
      scriptHash?: BytesLike | null,
      to?: string | null,
      value?: null,
      data?: null
    ): ScriptSpentEventFilter;
    ScriptSpent(
      scriptHash?: BytesLike | null,
      to?: string | null,
      value?: null,
      data?: null
    ): ScriptSpentEventFilter;
  };
=======
  filters: {};
>>>>>>> 09bc438 (chore: Add typechain)

  estimateGas: {
    conditionsRoot(overrides?: CallOverrides): Promise<BigNumber>;

<<<<<<< HEAD
    lastAction(overrides?: CallOverrides): Promise<BigNumber>;

    numActions(overrides?: CallOverrides): Promise<BigNumber>;

    pendingAction(overrides?: CallOverrides): Promise<BigNumber>;

=======
>>>>>>> 09bc438 (chore: Add typechain)
    spend(
      _to: string,
      _value: BigNumberish,
      _data: BytesLike,
      _script: BytesLike,
      _proof: BytesLike[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    conditionsRoot(overrides?: CallOverrides): Promise<PopulatedTransaction>;

<<<<<<< HEAD
    lastAction(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    numActions(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pendingAction(overrides?: CallOverrides): Promise<PopulatedTransaction>;

=======
>>>>>>> 09bc438 (chore: Add typechain)
    spend(
      _to: string,
      _value: BigNumberish,
      _data: BytesLike,
      _script: BytesLike,
      _proof: BytesLike[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
